config/routes.rb
Rails.application.routes.draw do
  resources :surveys

  resources :infos

  root 'main#index'

  get 'thanks' => 'main#thanks'

end

app/models/info.rb
class Info < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]


  # GET /infos/new
  def new
    @info = Info.new
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to thanks_path, notice: 'Thanks!' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:email)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def thanks
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:date, :duration, :pay, :position, :full_part_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="form-group">
    <%= f.label :email, class: "sr-only" %>
    <%= f.text_field :email, placeholder: "Email Address", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Do it", class: "btn btn-info btn-lg" %>
  </div>
</div>
</div>
<% end %>

app/views/infos/new.html.erb
<p>Sign up for the easiest way to find your perfect intern.</p>

<%= render 'form' %>

<%#= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InternSted</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>

  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Ubuntu:400,700" %>

  <script src="//cdn.optimizely.com/js/2457980461.js"></script>


  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59441142-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
	<br/>
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-md-offset-2">
		  		<div class="well">
		  			<h1><%#= image_tag "student.png", class: "hat" %>
              <span class="glyphicon glyphicon-education"></span>
             Intern<span class="not-bold">Sted</span></h1>
		     		<%= yield %>
	        	</div>
	     	</div>
     </div>
	</div>
</body>
</html>

app/views/main/index.html.erb
<!-- <h3>Quit the career fair &amp; posting hustle. <br/>Here are rockstar interns at your finger tips.</h3><br/>
<%#= link_to "I'm In", new_info_path, class: "btn btn-success btn-lg" %> -->

<div class="row">
  <div class="col-md-4">
  	<div class="well">
  		<%= image_tag "pic1.png" %>
  		<h4>Web Designer</h4>
  		<ul>
  			<li>HTML, CSS, JQuery
        <li>Photoshop, Illustrator</li>
  			<li>GT Grad</li>
  			<li>People Person</li>
  		</ul>
      <p class="label label-success">Available Now</p> 
  	</div>
  </div>
   <div class="col-md-4">
  	<div class="well">
  		<%= image_tag "pic2.png" %>
  		<h4>Content Specialist</h4>
  		<ul>
  			<li>Social Media Guru</li>
        <li>Google Analytics &amp; SEO</li>
        <li>Blogging and Headlines</li>
        <li>Loves Chinese Food </li>
  		</ul> 
      <p class="label label-success">Available March 15</p> 
  	</div>
  </div>
   <div class="col-md-4">
  	<div class="well">
      <%= image_tag "pic5.png" %>
      <h4>Web Developer</h4>
      <ul>
        <li>JQuery, Angular, Node</li>
        <li>HTML/Haml</li>
        <li>CSS/SASS</li>
        <li>Big Game of Thrones Fan</li>
      </ul> 
      <p class="label label-success">Available Now</p>
  	</div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
  	<div class="well">
      <%= image_tag "pic6.png" %>
      <h4>Back End Developer</h4>
      <ul>
        <li>Ruby on Rails</li>
        <li>Postgres &amp; MySQL</li>
        <li>GA State Grad</li>
        <li>Peace Corps Alumni</li>
      </ul>
      <p class="label label-success">Available March</p> 
  	</div>
  </div>
   <div class="col-md-4">
  	<div class="well">
  		<%= image_tag "pic3.png" %>
      <h4>Graphic &amp; Web Designer</h4>
      <ul>
        <li>Typeography Expert</li>
        <li>HTML, CSS, Bootstrap</li>
        <li>Award-winning Portfolio</li>
        <li>Crossfit Addict</li>
      </ul> 
      <p class="label label-success">Available Now</p>
  	</div>
  </div>
   <div class="col-md-4">
  	<div class="well">
  	  <%= image_tag "pic4.png" %>
      <h4>Back End Developer</h4>
      <ul>
        <li>Postgres, MySQL</li>
        <li>Ruby on Rails, Java, C++</li>
        <li>Loves Startups</li>
        <li>Momma's Boy</li>
      </ul> 
      <p class="label label-success">Available April 1</p>
  	</div>
  </div>
</div>

<%= link_to "Find Out More!", new_survey_path, class: "btn btn-lg btn-primary" %>

app/views/main/thanks.html.erb
<p>Thanks for signing up! We'll keep you posted on any updates.</p>

app/views/surveys/_form.html.erb
<div id="survey">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <%= form_for(@survey) do |f| %>
      <% if @survey.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

          <ul>
          <% @survey.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label "Approximate start date?" %><br>
        <%= f.text_field :date, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "How long will the position last?" %><br>
        <%= f.text_field :duration, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "How much will it pay?" %><br>
        <%= f.text_field :pay, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "Is it technical or non-technical?" %><br>
        <%= f.text_field :position, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "Is it full or part time?" %><br>
        <%= f.text_field :full_part_time, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit "Find My Intern", class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Surveys</h2>

<table class="table">
  <thead>
    <tr>
      <th>Start Date</th>
      <th>Duration</th>
      <th>Pay</th>
      <th>Position</th>
      <th>Commitment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.date %></td>
        <td><%= survey.duration %></td>
        <td><%= survey.pay %></td>
        <td><%= survey.position %></td>
        <td><%= survey.full_part_time %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h2>Intern Matching Survey</h2>
<!-- <h3>Fill out this survey to get matched with an awesome intern.</h3>
 -->
<hr/>
<%= render 'form' %>

<%#= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @survey.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @survey.duration %>
</p>

<p>
  <strong>Pay:</strong>
  <%= @survey.pay %>
</p>

<p>
  <strong>Position:</strong>
  <%= @survey.position %>
</p>

<p>
  <strong>Full part time:</strong>
  <%= @survey.full_part_time %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>